# EET 2162-E242 (Digital Electronics) Lectures 1 & 2 & 3

<b>These lecture notes cover lectures occuring on 08/27/2018 (Lectures 1), 09/05/18 (Lectures 2), 09/17/18 (Lectures 3). Topics covered include the following: 

* Digital vs. Analog, Digital/Analog Systems
* Decimal, Binary, Hexidecimal (Base 16) counting system
* Decimal to Binary Conversion, Binary to Decimal Conversion, Hex/Bin/Dec Conversions
* Binary-Coded-Decimal (BCD) method, even and odd parity digits
* Logic gates, Truth Tables, Boolean Algebra

Notes will be convered in concise sections, all shown below...
</b>

### Digital vs. Analog

* Analog tends to be defined as something that is continuous.
* Analog Representation—a continuously variable, proportional indicator.

    * Sound through a microphone causes voltage changes.

    * Automobile speedometer changes with speed.

    * Mercury thermometer varies over a range of values with temperature.


* Digital tends to be defined as something that is discrete (having seperate distinct states)
* Digital Representation—varies in discrete (separate) states.

    * Passing time is shown as a change in the display on a digital clock at one minute intervals.

    * A change in temperature is shown on a digital display only when the temperature changes at least one tenth of degree.

### Digital/Analog Systems

* Analog system: A combination of devices designed to manipulate signals in analog form

    * Examples of Analog system: Volume control of receiver, audio amplifiers, etc.
    

* Digital system: A combination of devices designed to manipulate signals in digital form

    * A large part of the worldwide telecommunications system falls in the category of “digital systems.”
    
    * Digital circuits have inputs that are in one of two states: 1 (on/True) or 0 (off/False). The outputs are also either producing a 1 or a 0.
    
        * In terms of voltages, "on" operates between the 2 $V$  to 5 $V$ range and "off" operates between the 0 $V$  to 2 $V$ range. This creates a square wave.
    <p></p>
    * Examples of Digital system: Computers, Calculators, Digital audio/video systems, etc.

#### Advantages/Chief reasons of/to switch to digital techniques:

* Ease of design, on/off, high/ low
* Well suited for storing information.
* Accuracy and precision are easier to maintain.(no distortion)
* Programmable operation.
* Less affected by noise.(high/low)
* Ease of fabrication on IC chips.

#### Limits to digital techniques:

* Signal in the real world is analog.
* The analog nature of the world requires a time consuming conversion process:

    * Convert the physical variable to an electrical signal (analog).
    * Convert the analog signal to digital form. 
    * Process (operate on) the digital information.
    * Convert the digital output back to real- world analog form.

### Decimal, Binary, Hexidecimal (Base 16), Octal (Base 8) counting system

* Decimal – 10 symbols (base 10)
    
    * ...$10^3$, $10^2$, $10^1$, $10^0$, $10^{-1}$, $10^{-2}$...
    
    
* Binary – 2 symbols (base 2)

    * Binary is one of many counting systems that are present within the world. It is mostly intertwined and familiarized with computing systems. In comparison to the base 10 counting system in which we are familiar, also known as the "Decimal" counting system, binary is of base 2. This means that instead of counting up to 9 (0, 1, 2, 3, 4, 5, 6, 7, 8, 9) like we are used to before shifting to the 10's place, we count up to 1 (0, 1) before shifting over to the next place. Also in binary the 10s place will instead be referred to as the 2's place since it is base 2. (E.g.:...$2^3$, $2^2$, $2^1$, $2^0$, $2^{-1}$, $2^{-2}$...)
    

* Hexadecimal – 16 symbols (base 16) 

    * ...$16^3$, $16^2$, $16^1$, $16^0$, $16^{-1}$, $16^{-2}$...
    

* Octal – 8 symbols (base 8)

    * ...$8^3$, $8^2$, $8^1$, $8^0$, $8^{-1}$, $8^{-2}$...

### Decimal to Binary Conversion, Binary to Decimal Conversion, Hex/Bin/Dec Conversions

#### How to convert from Decimal to Binary?

* ** Integer Part ** - to convert integer to binary you have to divide by 2. If you get a remainder of either "1" or "0", write it down like so:
    
#### Example

In [13]:
import pandas as pd
data = {'x': [52, 26, 13, 6, 3, 1],
        'x / 2' : ["52 / 2 =","26 / 2 =","13 / 2 =","7 / 2 =","3 / 2 =","1 / 2 = "],
        'A': [26, 13, 6, 3, 1, 0],
        'R': [0, 0, 1, 0, 1,1]}
        
df = pd.DataFrame.from_dict(data)
df

    x     x / 2   A  R
0  52  52 / 2 =  26  0
1  26  26 / 2 =  13  0
2  13  13 / 2 =   6  1
3   6   7 / 2 =   3  0
4   3   3 / 2 =   1  1
5   1  1 / 2 =    0  1

* Once you compute the division process, read all recorded remainders from the <b>bottom of the list to the top</b>. That will be the binary representation of decimal numbers.

$$52_{10} = 110100_{2}$$


* Fraction Part - to convert fractions or decimals to binary you have to multiply by 2.

#### For Decimals

* Multiply the decimal you're trying to convert by "2". For your results in the form of "n.a", place the ".a" portion of the result in the ".a" column, put the "n" portion in the "n" column. The "n" column should only have "0's" and "1's". Repeating numbers repeat ad infinitum so use the ( ""$\overline{\space\space\space\space\space\space}$" " ) over the repeating portion to indicate repeating numbers. You read the "n" column <b>top-down</b>.

In [14]:
data1 = {'x': [.3, .6, .2, .4, .8, .6, .2, .4, .8],
        'x * 2' : [".3 * 2 =",".6 * 2 =",".2 * 2 =",".4 * 2 =",".8 * 2 =",".6 * 2 =", ".2 * 2 =",".4 * 2 =",".8 * 2 ="],
        'N.A': [.6, 1.2, .4, .8, 1.6, 1.2, .4, .8, 1.6],
        'A': [.6, .2, .4, .8, .6, .2, .4, .8, .6],
        'n': [0, 1, 0, 0, 1, 1, 0, 0, 1]}
        
df1 = pd.DataFrame.from_dict(data1)
df1

     x     x * 2  N.A    A  n
0  0.3  .3 * 2 =  0.6  0.6  0
1  0.6  .6 * 2 =  1.2  0.2  1
2  0.2  .2 * 2 =  0.4  0.4  0
3  0.4  .4 * 2 =  0.8  0.8  0
4  0.8  .8 * 2 =  1.6  0.6  1
5  0.6  .6 * 2 =  1.2  0.2  1
6  0.2  .2 * 2 =  0.4  0.4  0
7  0.4  .4 * 2 =  0.8  0.8  0
8  0.8  .8 * 2 =  1.6  0.6  1

* since it's a repeating bit it is read as the following: $.0\overline{1001}$

#### For Fractions

* Multiply the fraction you're trying to convert by "2". For your results in the form of a mixed number, place the fraction portion of the result in the ".a" column, put the whole number portion in the "n" column. the "column" should only have "0's" and "1's". Repeating numbers repeat ad infinitum so use the ( "$\overline{\space\space\space\space\space\space}$" ) over the repeating portion to indicate repeating numbers. You read the "n" column top-down.

In [15]:
data2 = {'x': ['1/3','2/3','1/3','2/3','1/3','2/3','1/3','2/3','1/3'],
        'x * 2' : ['1/3 * 2 =','2/3 * 2 =','1/3 * 2 =','2/3 * 2 =','1/3 * 2 =','2/3 * 2 =','1/3 * 2 =','2/3 * 2 =','1/3 * 2 ='],
        'N.A': ['2/3','1*(1/3)','2/3','1*(1/3)','2/3','1*(1/3)','2/3','1*(1/3)','2/3'],
        'A': ['2/3','1/3','2/3','1/3','2/3','1/3','2/3','1/3','2/3'],
        'n': [0, 1, 0, 1, 0, 1, 0, 1, 0]}
        
df2 = pd.DataFrame.from_dict(data2)
df2

     x      x * 2      N.A    A  n
0  1/3  1/3 * 2 =      2/3  2/3  0
1  2/3  2/3 * 2 =  1*(1/3)  1/3  1
2  1/3  1/3 * 2 =      2/3  2/3  0
3  2/3  2/3 * 2 =  1*(1/3)  1/3  1
4  1/3  1/3 * 2 =      2/3  2/3  0
5  2/3  2/3 * 2 =  1*(1/3)  1/3  1
6  1/3  1/3 * 2 =      2/3  2/3  0
7  2/3  2/3 * 2 =  1*(1/3)  1/3  1
8  1/3  1/3 * 2 =      2/3  2/3  0

* since it's a repeating bit it is read as the following: $.\overline{0101}$


#### How to convert from Binary to Decimal?

* Integer Part - to convert binary to integer you have to multiply by a power of 2. After you'll add the digits together as see below

$$110100_{2} = (1 * 2^5) + (1 * 2^4) + (0 * 2^3) + (1 * 2^2) + (0 * 2^1) + (0 * 2^2) = 32 + 16 + 0 + 4 + 0 + 0 = 52_{10}$$

* Starting from the rightmost place you have the 2s, 4s, 8s, up until the 32s place. You multiply the digit by its place and add up all the products, as seen above, to convert the binary number into decimal.

#### Fractional Part 1:

* To convert terminating binary to a fractional part you have to multiply by a power of 2. After you'll add the digits together as see below. This method will only work if the fraction produced a terminating binary number.  

$$.1101 = (1 * 2^{-1})  + (1 * 2^{-2}) + (0 * 2^{-3}) + (1 * 2^{-4}) = \frac{1}{2} + \frac{1}{4} + 0 + \frac{1}{16} = \frac{13}{16}$$

* Starting from the leftmost place you have the 1/2s, 1/4s, 1/8s, up until the 1/32s place. You multiply the digit by its place and add up all the products, as seen above, to convert the binary number into decimal.

#### Fractional Part 2 

* To convert not terminating binary to a fractional part you have to use the shift property of multiplication by 2.

$$.\overline{1011}$$

* $.\overline{1011}_{2}$ is to be converted to a fraction. Set "x" to equal $.\overline{1011}_{2}$. 

$$x = .\overline{1011}_{2}$$

* Then multiply "x" by 2^4, which shifts 4 places to the left in binary. 

$$x = .\overline{1011}_{2}$$  
$$(2^4)x = 1011.\overline{1011}_{2}$$    

* Then subtract the original "x" from (2^4)x.

$$(2^4)x - x = 1011.\overline{1011}_{2} - .\overline{1011}_{2} = 1011_{2}$$

* Convert to decimal

$$1011_{2} = 1*2^3 + 0 + 1*2^1 + 1*2^0 = 11$$

* Solve for "x".

$$(2^4)x = 11$$  
$$16x = 11$$  
$$x = \frac{11}{16}$$  

* $\frac{11}{16}$ is the decimal of the repeating binary number.

#### How to Convert from Bin to Hex

* Group bits in 4's and convert each grouping of 4 to it's hex equivalent. This is shown below:

$$110100_{2} \rightarrow 0011_{2} = 3_{16};\space 0100_{2} = 8_{16} \rightarrow 34_{16}$$


#### How to Convert from Hex to Bin

* Convert each Hex digit to it binary value (make sure the bits are groups of 4) then combine. This is shown below: 

$$34_{16} \rightarrow 3_{16} = 0011_{2};\space 8_{16} = 0100_{2} \rightarrow 110100_{2}$$

#### How to Convert from Hex to Dec

* Multiply each hex digit by a power of 16 depending on its positioning. This is shown below:

$$34_{16} = 3 * 16^1 + 4 * 16^0 = 48 + 4 = 52_{10}$$

#### How to Convert from Dec to Hex

* Same procedure you have to find the binary equivalent. Do an operation of $\text{mod } 16$ until you get to zero and read the grouping of remainders from **bottom-up**. An example is shown below.

In [16]:
data3 = {'x': [52, 3],
        'x / 16' : ["52 / 16 =","3 / 16 ="],
        'A': [3, 0],
        'R': [4, 3]}
        
df3 = pd.DataFrame.from_dict(data3)
df3

    x     x / 16  A  R
0  52  52 / 16 =  3  4
1   3   3 / 16 =  0  3

### Binary-Coded-Decimal (BCD) method, even and odd parity digits

#### Binary-Coded-Decimal (BCD) method

* Binary Coded Decimal (BCD) is a widely used way to present decimal numbers in binary form.

    * It Combines features of both decimal and binary systems.
    • Each digit is converted to a binary equivalent.
    
    
* BCD is not a number system.

    * It is a decimal number with each digit encoded to its binary equivalent.
    
    
* A BCD number is not the same as a straight binary number.
    
    * The primary advantage of BCD is the relative ease of converting to and from decimal.


#### Decimal to BCD

* To convert Decimal to BCD, you just have to represent each decimal digit as a 4-digit binary equivalent. See Below:

$$873_{10} \rightarrow [1000][0111][0011] \rightarrow 100001110011_{2}$$

#### BCD to Decimal

* To convert from BCD to Decimal you just have to group to BCD digits by 4 starting from the leftmost (LSD, least significant digit) bit. The convert each group of 4 bits to their Decimal Equivalent. See Below:

$$100001110011_{2} \rightarrow [1000][0111][0011] \rightarrow 873_{10} $$


#### Even Parity Bits

* Even parity method: <b><i>"The total number of 1s in the code group including the parity bit must be an even number"</i></b>.

    * The binary group $1011$ would require the addition of a parity bit 1, making the group $11011$.

    * The parity bit may be added at either end of a group.

#### Odd Parity Bits

* Odd parity method: <b><i>"The total number of 1s in a code group including the parity bit must add up to an odd number"</i></b>.

    * The binary group $1 1 1 1$ would require the addition of a parity bit 1, making the group $1 1 1 1 1$.
    
    * The parity bit may be added at either end of a group.

### Functions

In [17]:
import math as m
import numpy as np

In [30]:
def dec_to_diffBase(number, base= 2, switch= 1):
    """This function converts numbers from base 10 (decimal) to other number systems.
    [E.g.: base 2 (bin), base 16 (hex), base 8 (octal)]. By default it converts from dec to bin.
    It takes in one argument, number, which is expected to be base 10. 
    It returns the number as a base 2 number."""
    binList = []
    if number == 0:
        binString = 0
        if switch == 1:
                binString = str(binString) + ' base ' + str(base)
        return str(binString)*4
    
    while number != 0:
        
        remainder = number % base
        
        if base == 16:
            if remainder == 10:
                remainder = 'a'
            elif remainder == 11:
                remainder = 'b'
            elif remainder == 12:
                remainder = 'c'
            elif remainder == 13:
                remainder = 'd'
            elif remainder == 14:
                remainder = 'e'
            elif remainder == 15:
                remainder = 'f'
            
        binList.append(remainder)
        number = number//base
        
        if number == 0:
            binList.reverse()
            binString = ''.join(str(i) for i in binList)
            if switch == 1:
                binString = binString + ' base ' + str(base)
            return binString

In [31]:
def diffBase_to_dec(number, base= 2):
    """This function converts numbers from other number systems to base 10 (decimal).
    [E.g.: base 2 (bin), base 16 (hex), base 8 (octal)]. By default it converts from bin to dec.
    It takes in one argument, number, which is expected to be other number systems. 
    It returns the number as a base 10 number."""
    number = list(str(number))
    number.reverse()
    decList = []
    for i in range(0,len(number)):
        
        if base == 16:
            if number[i] == 'a':
                number[i] = 10
            elif number[i] == 'b':
                number[i] = 11
            elif number[i] == 'c':
                number[i] = 12
            elif number[i] == 'd':
                number[i] = 13
            elif number[i] == 'e':
                number[i] = 14
            elif number[i] == 'f':
                number[i] = 15
        
        digit = int(number[i]) * m.pow(base, i)
        decList.append(digit)
    arr1 = np.array(decList)
    return np.sum(arr1)

In [43]:
def hex_to_bin(number, base= 16, switch= 1):
    """This function converts numbers from hex to base 2 (bin).
    It takes in one argument, number, which is expected to be hex. 
    It returns the number as a base 2 number."""
    number = list(str(number))
    for i in range(0,len(number)):
        
        if base == 16:
            if number[i] == 'a':
                number[i] = 10
            elif number[i] == 'b':
                number[i] = 11
            elif number[i] == 'c':
                number[i] = 12
            elif number[i] == 'd':
                number[i] = 13
            elif number[i] == 'e':
                number[i] = 14
            elif number[i] == 'f':
                number[i] = 15
    
    number = list(map(int, number))            
    bit = [dec_to_diffBase(hexDgt, switch= 0) for hexDgt in number]
    output = ''
    for binary in bit:
        output = output + binary
    return int(output)

In [44]:
bit = hex_to_bin('2c0')
bit

1011000000

In [34]:
dec_to_diffBase(8)

'1000 base 2'