<b>Name: Christ-Brian Amedjonekou  
Date: 10/29/2018  
EET 2162 (Digital Electronics) Lab Test 1  
Fall 2018, Section: E242, Code: 35757  
Instructor: Youngsik Song  </b>

# Construct Truth Table for the System

In [1]:
import pandas as pd

In [7]:
data2 = {'A': [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1], 
         'B': [0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1],
         'C': [0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1], 
         'D': [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
         'output': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1]
        }

In [8]:
df2 = pd.DataFrame.from_dict(data2)

In [9]:
df2

    A  B  C  D  output
0   0  0  0  0       0
1   0  0  0  1       0
2   0  0  1  0       0
3   0  0  1  1       0
4   0  1  0  0       0
5   0  1  0  1       0
6   0  1  1  0       0
7   0  1  1  1       0
8   1  0  0  0       0
9   1  0  0  1       0
10  1  0  1  0       0
11  1  0  1  1       0
12  1  1  0  0       1
13  1  1  0  1       0
14  1  1  1  0       0
15  1  1  1  1       1

# From the truth table generate a Sum of Product Equation

$\textbf{output} = (ABCD + AB\bar{C}\bar{D})(\bar{A}\bar{B}\bar{C}\bar{D} + \bar{A}\bar{B}\bar{C}D + \bar{A}\bar{B}C\bar{D} + \bar{A}\bar{B}CD + \bar{A}B\bar{C}\bar{D} + \bar{A}B\bar{C}D + \bar{A}BC\bar{D} + \bar{A}BCD + A\bar{B}\bar{C}\bar{D} + A\bar{B}\bar{C}D + A\bar{B}C\bar{D} + A\bar{B}CD + AB\bar{C}D + ABC\bar{D})$

$\textbf{Let X} = (ABCD + AB\bar{C}\bar{D})$  


$\textbf{Let Y} = (\bar{A}\bar{B}\bar{C}\bar{D} + \bar{A}\bar{B}\bar{C}D + \bar{A}\bar{B}C\bar{D} + \bar{A}\bar{B}CD + \bar{A}B\bar{C}\bar{D} + \bar{A}B\bar{C}D + \bar{A}BC\bar{D} + \bar{A}BCD + A\bar{B}\bar{C}\bar{D} + A\bar{B}\bar{C}D + A\bar{B}C\bar{D} + A\bar{B}CD + AB\bar{C}D + ABC\bar{D})$

$\textbf{output} = XY$

# Simplify SOP using Boolean Theorems

$\textbf{X} = (ABCD + AB\bar{C}\bar{D})$  

* Simplifies to...

$\textbf{X} = AB(CD + \bar{C}\bar{D})$ 

* Simplifies further to...

$\textbf{X} = AB$ 

* And

$\textbf{Y} = (\bar{A}\bar{B}\bar{C}\bar{D} + \bar{A}\bar{B}\bar{C}D + \bar{A}\bar{B}C\bar{D} + \bar{A}\bar{B}CD + \bar{A}B\bar{C}\bar{D} + \bar{A}B\bar{C}D + \bar{A}BC\bar{D} + \bar{A}BCD + A\bar{B}\bar{C}\bar{D} + A\bar{B}\bar{C}D + A\bar{B}C\bar{D} + A\bar{B}CD + AB\bar{C}D + ABC\bar{D})$

* Simplifies to

$\textbf{Y} = \bar{A}\bar{B}\bar{C}(\bar{D} + D) + \bar{A}\bar{B}C(\bar{D} + D) + \bar{A}B\bar{C}(\bar{D} + D) + \bar{A}BC(\bar{D} + D) + A\bar{B}\bar{C}(\bar{D} + D) + A\bar{B}C(\bar{D} + D) + AB(\bar{C}D + C\bar{D}))$

* Simplifies further to

$\textbf{Y} = \bar{A}\bar{B}\bar{C} + \bar{A}\bar{B}C + \bar{A}B\bar{C} + \bar{A}BC + A\bar{B}\bar{C} + A\bar{B}C + AB(\bar{C}D + C\bar{D}))$

* Simplifies further to

$\textbf{Y} = \bar{A}\bar{B}(\bar{C} + C) + \bar{A}B(\bar{C} + C) + A\bar{B}(\bar{C} + C) + AB(\bar{C}D + C\bar{D}))$

* Simplifies further to

$\textbf{Y} = \bar{A}\bar{B} + \bar{A}B + A\bar{B} + AB(\bar{C}D + C\bar{D})$

* Simplifies further to

$\textbf{Y} = \bar{A}(\bar{B} + B) + A\bar{B} + AB(\bar{C}D + C\bar{D})$

* Simplifies further to

$\textbf{Y} = \bar{A} + A(\bar{B} + B(\bar{C}D + C\bar{D})))$


$\textbf{output} = XY = \big(AB\big) \big(\bar{A} + A(\bar{B} + B\bar{C}D + BC\bar{D})\big)$